services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloudsuites'
      - 'POSTGRES_PASSWORD=cspassword'
      - 'POSTGRES_USER=csuser'
    ports:
      - "59665:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: cs@cloudsuites.com
      PGADMIN_DEFAULT_PASSWORD: cspassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data: