services:
  postgres:
    image: postgres:17
    container_name: cloudsuites-postgres-17
    environment:
      - 'POSTGRES_DB=cloudsuites'
      - 'POSTGRES_PASSWORD=csPassw0rd'
      - 'POSTGRES_USER=csuser'
    ports:
      - "59665:5432"
    volumes:
      - new_pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: cs@cloudsuites.com
      PGADMIN_DEFAULT_PASSWORD: cspassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  new_pg_data: