# CloudSuites Application Configuration
# Docker-First Development Environment
# =================================================================

logging:
  level:
    root: INFO
    com.cloudsuites: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema: DEBUG
    org.springframework.orm.jpa: DEBUG
    com.fasterxml.jackson.databind: DEBUG
  pattern:
    console: "%-4relative [%thread] %-5level %logger{35} %X{correlationId} - %msg %n"

# =================================================================
# SPRING CONFIGURATION
# =================================================================
spring:
  # Docker Compose Integration
  docker:
    compose:
      file: ../../compose.yaml  # Point to root directory compose file
      lifecycle-management: start-only  # Only start, don't stop
      skip:
        in-tests: true  # Skip Docker Compose integration in tests
  # Database Configuration (Docker PostgreSQL)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Flyway Database Migration
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    enabled: true  # ENABLED - Using Flyway for schema management
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    placeholders:
      partitioning.prefix: "amenity_booking_"
      partitioning.frequency: "4"
      partitioning.retention_period_months: "3"
      partitioning.archive_storage_path: "/app/storage"
      archiving.cut_off_period_months: "6"
      archiving.file_format: ".parquet"
      interval.months: "1"
      interval.quarters: "3"
      interval.years: "12"

  # R2DBC Configuration (Reactive)
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: postgresql
    pools:
      initial-size: ${SPRING_R2DBC_POOL_INITIAL_SIZE}
      max-size: ${SPRING_R2DBC_POOL_MAX_SIZE}

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl.auto: none  # DISABLED - Using Flyway for schema management
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        show_sql: true
        format_sql: true

  # SQL Initialization
  sql:
    init:
      mode: always

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

  # Web Configuration
  web:
    resources:
      static-locations: classpath:/static/

  # Redis Configuration (for rate limiting and caching)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}  # Use database 1 for rate limiting
      timeout: ${REDIS_TIMEOUT:2000ms}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:0}
          max-wait: ${REDIS_POOL_MAX_WAIT:-1ms}
      password: ${REDIS_PASSWORD:}

# =================================================================
# EXTERNAL INTEGRATIONS
# =================================================================

# Auth0 Configuration
auth0:
  audience: ${AUTH0_AUDIENCE}

# CORS Configuration  
web:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

# Okta Configuration (if needed)
okta:
  oauth2:
    groupsClaim: https://api.cloudsuites.com/roles

# Twilio SMS Configuration
twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  serviceSid: ${TWILIO_SERVICE_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}

# JWT Configuration (Enhanced with RSA-256)
jwt:
  # RSA-256 signing (replaces HMAC for enhanced security)
  issuer: ${JWT_ISSUER:cloudsuites}
  audience: ${JWT_AUDIENCE:CloudSuites}
  
  # Enhanced token validity periods (REQ-003)
  access-token-validity-minutes: ${JWT_ACCESS_TOKEN_VALIDITY_MINUTES:15}   # 15 minutes
  refresh-token-validity-days: ${JWT_REFRESH_TOKEN_VALIDITY_DAYS:30}       # 30 days
  
  # Backward compatibility (deprecated - use RSA keys instead)
  secretKey: ${JWT_SECRET_KEY:deprecated_use_rsa_keys}
  accessTokenValidityMs: ${JWT_ACCESS_TOKEN_VALIDITY_MS:900000}    # 15 minutes  
  refreshTokenValidityMs: ${JWT_REFRESH_TOKEN_VALIDITY_MS:2592000000}  # 30 days

# Google Cloud Platform
gcp:
  firebase:
    service-account: ${GCP_FIREBASE_SERVICE_ACCOUNT}

# =================================================================
# MONITORING & MANAGEMENT
# =================================================================

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,env,beans,auditevents,loggers,configprops,threaddump,heapdump,dependencies
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    loggers:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# =================================================================
# SERVER CONFIGURATION
# =================================================================

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
  compression:
    enabled: true
  forward-headers-strategy: framework

# =================================================================
# APPLICATION-SPECIFIC CONFIGURATION
# =================================================================

cloudsuites:
  app:
    name: CloudSuites Property Management
    version: '@project.version@'
  storage:
    upload-path: ${UPLOAD_PATH}
    max-file-size: ${MAX_FILE_SIZE}
  
  # Rate Limiting Configuration
  rate-limiting:
    enabled: ${RATE_LIMITING_ENABLED:true}
    redis-enabled: ${RATE_LIMITING_REDIS_ENABLED:true}
    
    # Default configurations for common operations
    configurations:
      login:
        limit: ${RATE_LIMIT_LOGIN_ATTEMPTS:5}
        window-minutes: ${RATE_LIMIT_LOGIN_WINDOW_MINUTES:15}
        enable-lockout: ${RATE_LIMIT_LOGIN_ENABLE_LOCKOUT:true}
        lockout-threshold: ${RATE_LIMIT_LOGIN_LOCKOUT_THRESHOLD:5}
      
      otp_send:
        limit: ${RATE_LIMIT_OTP_SEND_ATTEMPTS:3}
        window-minutes: ${RATE_LIMIT_OTP_SEND_WINDOW_MINUTES:5}
        enable-lockout: ${RATE_LIMIT_OTP_SEND_ENABLE_LOCKOUT:false}
        lockout-threshold: ${RATE_LIMIT_OTP_SEND_LOCKOUT_THRESHOLD:10}
      
      otp_verify:
        limit: ${RATE_LIMIT_OTP_VERIFY_ATTEMPTS:5}
        window-minutes: ${RATE_LIMIT_OTP_VERIFY_WINDOW_MINUTES:5}
        enable-lockout: ${RATE_LIMIT_OTP_VERIFY_ENABLE_LOCKOUT:true}
        lockout-threshold: ${RATE_LIMIT_OTP_VERIFY_LOCKOUT_THRESHOLD:5}
      
      password_reset:
        limit: ${RATE_LIMIT_PASSWORD_RESET_ATTEMPTS:3}
        window-minutes: ${RATE_LIMIT_PASSWORD_RESET_WINDOW_MINUTES:60}
        enable-lockout: ${RATE_LIMIT_PASSWORD_RESET_ENABLE_LOCKOUT:false}
        lockout-threshold: ${RATE_LIMIT_PASSWORD_RESET_LOCKOUT_THRESHOLD:5}
      
      registration:
        limit: ${RATE_LIMIT_REGISTRATION_ATTEMPTS:3}
        window-minutes: ${RATE_LIMIT_REGISTRATION_WINDOW_MINUTES:60}
        enable-lockout: ${RATE_LIMIT_REGISTRATION_ENABLE_LOCKOUT:true}
        lockout-threshold: ${RATE_LIMIT_REGISTRATION_LOCKOUT_THRESHOLD:3}
    
    # Lockout configuration
    lockout:
      # Exponential backoff durations in minutes
      base-duration-minutes: ${RATE_LIMIT_LOCKOUT_BASE_DURATION_MINUTES:1}
      max-duration-minutes: ${RATE_LIMIT_LOCKOUT_MAX_DURATION_MINUTES:1440}  # 24 hours
      multiplier: ${RATE_LIMIT_LOCKOUT_MULTIPLIER:5}
      
    # Fallback configuration when Redis is unavailable
    in-memory:
      max-entries: ${RATE_LIMIT_IN_MEMORY_MAX_ENTRIES:10000}
      cleanup-interval-minutes: ${RATE_LIMIT_IN_MEMORY_CLEANUP_INTERVAL_MINUTES:5}
  
  # Device Trust Configuration
  device-trust:
    enabled: ${DEVICE_TRUST_ENABLED:true}
    default-expiration-days: ${DEVICE_TRUST_DEFAULT_EXPIRATION_DAYS:30}
    max-devices-per-user: ${DEVICE_TRUST_MAX_DEVICES_PER_USER:10}
    fingerprint-algorithm: ${DEVICE_TRUST_FINGERPRINT_ALGORITHM:SHA-256}
    trusted-token-duration-minutes: ${DEVICE_TRUST_TOKEN_DURATION_MINUTES:43200}  # 30 days
    risk-threshold: ${DEVICE_TRUST_RISK_THRESHOLD:70}
    
    # Cleanup configuration
    cleanup:
      enabled: ${DEVICE_TRUST_CLEANUP_ENABLED:true}
      interval-hours: ${DEVICE_TRUST_CLEANUP_INTERVAL_HOURS:24}
      inactive-threshold-days: ${DEVICE_TRUST_INACTIVE_THRESHOLD_DAYS:90}
      
    # Security settings
    security:
      require-mfa-for-high-risk: ${DEVICE_TRUST_REQUIRE_MFA_HIGH_RISK:true}
      block-critical-risk: ${DEVICE_TRUST_BLOCK_CRITICAL_RISK:true}
      track-ip-changes: ${DEVICE_TRUST_TRACK_IP_CHANGES:true}
