logging:
  level:
    root: INFO
    com.cloudsuites.framework: DEBUG
  pattern:
    console: "%-4relative [%thread] %-5level %logger{35} %X{correlationId} - %msg %n"
spring:
  sql:
    init:
      mode: embedded
  db:
    url: jdbc:postgresql://localhost:5432/cloudsuites
    username: csuser
    password: csPassw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        show_sql: false
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudsuites
    username: csuser
    password: csPassw0rd
    driver-class-name: org.postgresql.Driver
  web:
    resources:
      static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,env,beans,auditevents,loggers,configprops,threaddump,heapdump,dependencies
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true