logging:
  level:
    root: INFO
    com.cloudsuites.framework: DEBUG
  pattern:
    console: "%-4relative [%thread] %-5level %logger{35} %X{correlationId} - %msg %n"
spring:
  sql:
    init:
      mode: embedded
  db:
    url: jdbc:postgresql://cloudsuites.postgres.database.azure.com:5432/cloudsuites?user=csuser&password=csPassw0rd&sslmode=require
    username: csuser
    password: csPassw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        show_sql: false
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://cloudsuites.postgres.database.azure.com:5432/cloudsuites?user=csuser&password=csPassw0rd&sslmode=require
    username: csuser
    password: csPassw0rd
    driver-class-name: org.postgresql.Driver
  web:
    resources:
      static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,env,beans,auditevents,loggers,configprops,threaddump,heapdump,dependencies
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
twilio:
  accountSid: ${accountSid}
  serviceSid: ${serviceSid}
  authToken: ${authToken}
  phoneNumber: ${phoneNumber}
jwt:
  secretKey: ${secretKey}
  accessTokenValidityMs: 86400000  # 1 day in milliseconds
  refreshTokenValidityMs: 604800000  # 7 days in milliseconds
gcp:
  firebase:
    service-account: classpath:firebase-service-account.json