name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    env:
      # Test Database Configuration (matches application-test.yml)
      TEST_DATABASE_URL: jdbc:postgresql://localhost:5432/cloudsuites_dev
      TEST_DATABASE_USERNAME: cloudsuites_user
      TEST_DATABASE_PASSWORD: cloudsuites_dev
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: cloudsuites_dev
      DB_USERNAME: cloudsuites_user
      DB_PASSWORD: cloudsuites_dev
      # Production Database Configuration (fallback)
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cloudsuites_dev
      SPRING_DATASOURCE_USERNAME: cloudsuites_user
      SPRING_DATASOURCE_PASSWORD: cloudsuites_dev
    
    strategy:
      matrix:
        java-version: [21]
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: cloudsuites_dev
          POSTGRES_USER: cloudsuites_user
          POSTGRES_DB: cloudsuites_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
        
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          dependency-submission: disabled   # <-- key change
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
        
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
      - name: Verify Maven wrapper and settings
        run: |
          test -f ./mvnw || { echo "mvnw missing"; exit 1; }
          test -f .mvn/settings.xml || { echo ".mvn/settings.xml missing"; exit 1; }
      
      - run: chmod +x ./mvnw
      
      - run: ./mvnw --version
      - run: ./mvnw -s .mvn/settings.xml compile -Dfrontend.skip=true
      - run: ./mvnw -s .mvn/settings.xml test -Dfrontend.skip=true
      - run: ./mvnw -s .mvn/settings.xml package -DskipTests -Dfrontend.skip=true
